### ISSUE TITLE
Porting to BeagleBone Black

### ISSUE THREAD

**Issue by efargas** [hallard/ArduiPi_OLED#4]
I'm trying to port this to work with beaglebone.
Could you tell me the steps that i have to follow.
I supose that i have to write low level functions to beaglebone spi like your bcm2835.c frrom pi and pin mapping of gpios.

**Comment by hallard** [comment]
@efargas 
Well, bcm2835 is used to drive I2C and SPI, I don't know how I2C and SPI are working on beaglebone, but I think the easy way could be driving I2C would be to drive as "file" mode

You can see example here http://datko.net/2013/11/03/bbb_i2c/

**Comment by efargas** [comment]
I'm using [Derek's Moloy bus library](https://github.com/derekmolloy/exploringBB/tree/master/library/bus) to drive I2C and SPI devices so is not a problem.

I have a custom shared library made from Derek's Moloy with my additions and i will try to include in it the oled and gfx classes as part of the global library.

Is possible to build all the stuff together as a shared lib?
or build it apart each one


what wrapper.cpp do?

**Comment by devel0** [comment]
Wrapper.cpp is a bridge to export C functions into managed csharp code (see mono), it's not necessary for the c library I will adapt extending it if necessary. You can comment out from compilation (Makefile) at now if nedded to make changes.
